substitutions:
  _REGION: 'us-central1'
  _REPO: 'ledger-repo'
  _CLUSTER: 'bank-of-anthos'
  _NAMESPACE: 'default'
  _SERVICE_NAME: 'ledger-db'
  _CONTAINER_NAME: 'postgres' # Container name within the statefulset pod
  # Use '.' as the Dockerfile directory since this cloudbuild.yaml is inside the service directory
  _DOCKERFILE_DIR: '.'

steps:
  # 1) build ledger-db using Dockerfile
  - name: gcr.io/cloud-builders/docker
    # Run Docker build from the directory containing this cloudbuild.yaml
    dir: 'src/ledger/ledger-db'
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$SHORT_SHA'
      - '-f'
      - '${_DOCKERFILE_DIR}/Dockerfile'
      - '${_DOCKERFILE_DIR}'

  # 2) push ledger-db image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$SHORT_SHA'

  # 3) auth to GKE cluster
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials $_CLUSTER \
          --region $_REGION \
          --project $PROJECT_ID

  # 4) roll out new image (StatefulSet)
  - name: gcr.io/cloud-builders/kubectl
    env:
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
    args:
      - set
      - image
      - statefulset/$_SERVICE_NAME
      - $_CONTAINER_NAME=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$SHORT_SHA
      - --namespace=$_NAMESPACE

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE_NAME:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
