substitutions:
  _REGION: "us-central1"
  _REPO: "frontend-repo"
  _CLUSTER: "bank-of-anthos"
  _DEPLOYMENT: "frontend"
  _NAMESPACE: "default"

steps:
# 1) build & tag
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - "-t"
    - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend:$SHORT_SHA"
    - "-f"
    - "src/frontend/Dockerfile"
    - "src/frontend"

# 2) push to Artifact Registry
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend:$SHORT_SHA"

# 3) auth to your GKE cluster
- name: gcr.io/cloud-builders/gcloud
  volumes:
  - name: kube-config
    path: /root/.kube
  entrypoint: bash
  args:
    - "-c"
    - |
      gcloud container clusters get-credentials $_CLUSTER \
        --region $_REGION \
        --project $PROJECT_ID

# 4) roll out the new image
- name: gcr.io/cloud-builders/kubectl
  env:
    - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
    - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
  args:
    - set
    - image
    - deployment/$_DEPLOYMENT
    - frontend="$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend:$SHORT_SHA"
    - --namespace=$_NAMESPACE

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/frontend:$SHORT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY