substitutions:
  _REGION: 'us-central1'
  _REPO: 'accounts-repo'
  _CLUSTER: 'bank-of-anthos'
  _NAMESPACE: 'default'

steps:
  # 1) build & tag accounts-db
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/accounts-db:$SHORT_SHA'
      - '-f'
      - 'src/accounts/accounts-db/Dockerfile'
      - 'src/accounts/accounts-db'
  # 2) push accounts-db
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/accounts-db:$SHORT_SHA'

  # 3) build & tag contacts
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/contacts:$SHORT_SHA'
      - '-f'
      - 'src/accounts/contacts/Dockerfile'
      - 'src/accounts/contacts'
  # 4) push contacts
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/contacts:$SHORT_SHA'

  # 5) build & tag userservice
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/userservice:$SHORT_SHA'
      - '-f'
      - 'src/accounts/userservice/Dockerfile'
      - 'src/accounts/userservice'
  # 6) push userservice
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/userservice:$SHORT_SHA'

  # 7) auth to GKE cluster
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials $_CLUSTER \
          --region $_REGION \
          --project $PROJECT_ID

  # 8) roll out new images
  - name: gcr.io/cloud-builders/kubectl
    env:
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
    args:
      - set
      - image
      - statefulset/accounts-db
      - accounts-db=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/accounts-db:$SHORT_SHA
      - --namespace=$_NAMESPACE
  - name: gcr.io/cloud-builders/kubectl
    env:
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
    args:
      - set
      - image
      - deployment/contacts
      - contacts=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/contacts:$SHORT_SHA
      - --namespace=$_NAMESPACE
  - name: gcr.io/cloud-builders/kubectl
    env:
      - 'CLOUDSDK_COMPUTE_REGION=$_REGION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER'
    args:
      - set
      - image
      - deployment/userservice
      - userservice=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/userservice:$SHORT_SHA
      - --namespace=$_NAMESPACE

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/accounts-db:$SHORT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/contacts:$SHORT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/userservice:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
